[package]
name = "ruarango"
version = "0.1.0"
authors = ["Jason Ozias <jason.ozias@kroger.com>"]
edition = "2018"
autotests = false

[dependencies]
anyhow = "1"
async-trait = "0"
const_format = "0"
derive_builder = "0"
futures = "0"
getset = "0"
libeither = "0"
reqwest = { version = "0", features = [ "json" ] }
serde = "1"
serde_derive = "1"
serde_json = "1"
thiserror = "1"
wiremock = "0"

[dev-dependencies]
lazy_static = "1"
rand = "0"
r2d2 = "0"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
tokio-test = "0"
wiremock = "0"

[build-dependencies]
rustversion = "1"

[[test]]
name = "integration"
path = "tests/lib.rs"
